version: 2
updates:
  # Enable version updates for bundler
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly

  # Enable version updates for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # Enable version updates for Git Submodules
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
